services:
  rustapp:
    container_name: rustappnew
    image: aniketp02/rustappnew:latest
    build:
      dockerfile: rust.dockerfile
      args:
        DATABASE_URL: postgresql://user:password@127.0.0.1:5432/pincode-serviceability
        # REDIS_URL: "redis://redis:6380"
    network_mode: "host"
    # depends_on:
    #   - redis

  # redis:
  #   image: redis:latest
    # ports:
    #   - "6380:6380"  # Expose the Redis port
    # network_mode: "host"

volumes:
  pgdata: {}