[default]
address = "0.0.0.0"
port = 8083

[global]
limits = { file = 100000000, data-form = 100000000, form = 100000000}

[default.databases.pincode-serviceability]
url = "postgresql://user:password@127.0.0.1:5432/pincode-serviceability"